apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./deployment.yaml
- ./service.yaml
images:
- name: lcartwri/sl-flask-web-app
- name: lcartwri/web-demo-app
  newTag: b7b68f40d2fa8e6c0196abf2905ebf3e4f9052bb
