apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ./deployment.yaml
- ./service.yaml
images:
- name: lcartwri/sl-flask-web-app
- name: lcartwri/web-demo-app
  newTag: c5f057de113a2b1d3fe4e9426cb60cfa330eda70
